// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Aseme.HubSupplier.Shared.Infrastructure.Persistence.EntityFramework;

#nullable disable

namespace aseme_api.Migrations
{
    [DbContext(typeof(HubSuppliersDbContext))]
    [Migration("20230706063758_RenamedHttpLogTable")]
    partial class RenamedHttpLogTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("aseme_api.Features.Functionalities.Domain.Functionality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("Range", new[] { 0, 9999 })
                        .HasAnnotation("RequiredErrorMessage", "Id is required");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Descripcion")
                        .HasAnnotation("RequiredErrorMessage", "Descripcion is required");

                    b.HasKey("Id");

                    b.ToTable("Funcionalidad", (string)null);
                });

            modelBuilder.Entity("aseme_api.Features.HttpLogs.Domain.HttpLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("EntityId");

                    b.Property<int?>("ExecutionTime")
                        .HasColumnType("int")
                        .HasColumnName("ExecutionTime");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("HttpMethod")
                        .HasAnnotation("ErrorMessage", "HttpMethod is required");

                    b.Property<string>("HttpPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("HttpPath")
                        .HasAnnotation("ErrorMessage", "HttpPath is required");

                    b.Property<string>("HttpQueryParams")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("HttpQueryParams");

                    b.Property<string>("HttpRequestBody")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("HttpRequestBody");

                    b.Property<string>("HttpRequestHeaders")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("HttpRequestHeaders");

                    b.Property<string>("HttpResponseBody")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("HttpResponseBody");

                    b.Property<string>("HttpResponseHeaders")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("HttpResponseHeaders");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("int")
                        .HasColumnName("HttpStatusCode")
                        .HasAnnotation("ErrorMessage", "HttpStatusCode is required");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("IpAddress");

                    b.Property<DateTime>("ReceivedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ReceivedDateTime")
                        .HasAnnotation("ErrorMessage", "ReceivedDateTime is required");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Scheme")
                        .HasAnnotation("ErrorMessage", "Scheme is required");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("HttpStatusCode");

                    b.HasIndex("IpAddress");

                    b.HasIndex("ReceivedDateTime");

                    b.ToTable("HttpLog", (string)null);
                });

            modelBuilder.Entity("aseme_api.Features.OnlineMeters.Domain.OnlineMeterDetails", b =>
                {
                    b.Property<long>("OnlineMeterId")
                        .HasColumnType("bigint");

                    b.Property<int>("InstallationYear")
                        .HasColumnType("int")
                        .HasColumnName("InstallationYear");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Model");

                    b.Property<int>("Period")
                        .HasColumnType("int")
                        .HasColumnName("Period");

                    b.Property<DateTime>("ReadingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ReadingDate");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SerialNumber");

                    b.HasKey("OnlineMeterId");

                    b.HasIndex("Manufacturer");

                    b.HasIndex("ReadingDate");

                    b.HasIndex("SerialNumber");

                    b.ToTable("OnlineMeterDetails", (string)null);
                });

            modelBuilder.Entity("aseme_api.Features.RestoreIcps.Domain.RestoreIcpDetails", b =>
                {
                    b.Property<long>("RestoreIcpId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Description")
                        .HasAnnotation("RequiredErrorMessage", "Description is required");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExecutionDate")
                        .HasAnnotation("RequiredErrorMessage", "ExecutionDate is required");

                    b.Property<int>("RestoreIcpStatus")
                        .HasColumnType("int")
                        .HasColumnName("RestoreIcpStatus")
                        .HasAnnotation("RequiredErrorMessage", "RestoreIcpStatus is required");

                    b.HasKey("RestoreIcpId");

                    b.HasIndex("ExecutionDate");

                    b.HasIndex("RestoreIcpStatus");

                    b.ToTable("ResctoreIcpDetails", (string)null);
                });

            modelBuilder.Entity("aseme_api.Features.Roles.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("Range", new[] { 0, 9999 })
                        .HasAnnotation("RequiredErrorMessage", "Id is required");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Descripcion")
                        .HasAnnotation("RequiredErrorMessage", "Descripcion is required");

                    b.HasKey("Id");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("aseme_api.Features.RolesFunctionalities.Domain.RoleFunctionalities", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("IdRol")
                        .HasAnnotation("ErrorMessage", "RoleId is required")
                        .HasAnnotation("Range", new[] { 0, 9999 });

                    b.Property<int>("FunctionalityId")
                        .HasColumnType("int")
                        .HasColumnName("IdFuncionalidad")
                        .HasAnnotation("ErrorMessage", "FunctionalityId is required")
                        .HasAnnotation("Range", new[] { 0, 9999 });

                    b.Property<int>("IsQueryable")
                        .HasColumnType("int")
                        .HasColumnName("EsConsultableActivaEntrante")
                        .HasAnnotation("ErrorMessage", "IsQueryable is required")
                        .HasAnnotation("Range", new[] { 0, 9999 });

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Valor")
                        .HasAnnotation("ErrorMessage", "Value is required");

                    b.HasKey("RoleId", "FunctionalityId");

                    b.HasIndex("FunctionalityId");

                    b.ToTable("RolFuncionalidad", (string)null);
                });

            modelBuilder.Entity("aseme_api.Features.Shared.Operation.BaseOperation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Distributor")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("Distributor")
                        .HasAnnotation("RequiredErrorMessage", "Distributor is required");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("Distributor");

                    b.HasIndex("LastModifiedDate");

                    b.ToTable("BaseOperation", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("aseme_api.Features.Users.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("Range", new[] { 0, 9999 })
                        .HasAnnotation("RequiredErrorMessage", "Id is required");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorizedThirdPartyFilterMode")
                        .HasColumnType("int")
                        .HasColumnName("ModoFiltradoTercerosAutorizados")
                        .HasAnnotation("Range", new[] { 0, 9999 })
                        .HasAnnotation("RequiredErrorMessage", "ModoFiltradoTercerosAutorizados is required");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaAlta")
                        .HasAnnotation("RequiredErrorMessage", "FechaAlta is required");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaBaja")
                        .HasAnnotation("RequiredErrorMessage", "FechaBaja is required");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("EstaBorrado")
                        .HasAnnotation("RequiredErrorMessage", "EstaBorrado is required");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion")
                        .HasAnnotation("RequiredErrorMessage", "FechaModificacion is required");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Usuario")
                        .HasAnnotation("RequiredErrorMessage", "Usuario is required");

                    b.HasKey("Id");

                    b.ToTable("Logins", (string)null);
                });

            modelBuilder.Entity("aseme_api.Features.UsersRoles.Domain.UserRoles", b =>
                {
                    b.Property<int>("LoginUserId")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioLogin")
                        .HasAnnotation("Range", new[] { 0, 9999 })
                        .HasAnnotation("RequiredErrorMessage", "IdUsuarioLogin is required");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("IdRol")
                        .HasAnnotation("Range", new[] { 0, 9999 })
                        .HasAnnotation("RequiredErrorMessage", "IdRol is required");

                    b.HasKey("LoginUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuarioRol", (string)null);
                });

            modelBuilder.Entity("aseme_api.Features.OnlineMeters.Domain.OnlineMeter", b =>
                {
                    b.HasBaseType("aseme_api.Features.Shared.Operation.BaseOperation");

                    b.Property<long>("OnlineMeterDetailsOnlineMeterId")
                        .HasColumnType("bigint");

                    b.Property<int>("OperationStatus")
                        .HasColumnType("int")
                        .HasColumnName("OperationStatus")
                        .HasAnnotation("RequiredErrorMessage", "SupplyPoint is required");

                    b.Property<string>("SupplyPoint")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)")
                        .HasColumnName("SupplyPoint")
                        .HasAnnotation("RegularExpression", "[A-Z0-9]{1,22}")
                        .HasAnnotation("RequiredErrorMessage", "SupplyPoint is required");

                    b.HasIndex("OnlineMeterDetailsOnlineMeterId");

                    b.HasIndex("OperationStatus");

                    b.HasIndex("SupplyPoint");

                    b.ToTable("OnlineMeter", (string)null);
                });

            modelBuilder.Entity("aseme_api.Features.RestoreIcps.Domain.RestoreIcp", b =>
                {
                    b.HasBaseType("aseme_api.Features.Shared.Operation.BaseOperation");

                    b.Property<int>("OperationStatus")
                        .HasColumnType("int")
                        .HasColumnName("OperationStatus")
                        .HasAnnotation("RequiredErrorMessage", "OperationStatus is required");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SerialNumber");

                    b.Property<string>("SupplyPoint")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)")
                        .HasColumnName("SupplyPoint")
                        .HasAnnotation("RegularExpression", "[A-Z0-9]{1,22}")
                        .HasAnnotation("RequiredErrorMessage", "SupplyPoint is required");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("SupplyPoint");

                    b.ToTable("RestoreIcp", (string)null);
                });

            modelBuilder.Entity("aseme_api.Features.OnlineMeters.Domain.OnlineMeterDetails", b =>
                {
                    b.HasOne("aseme_api.Features.OnlineMeters.Domain.OnlineMeter", "OnlineMeter")
                        .WithOne()
                        .HasForeignKey("aseme_api.Features.OnlineMeters.Domain.OnlineMeterDetails", "OnlineMeterId");

                    b.Navigation("OnlineMeter");
                });

            modelBuilder.Entity("aseme_api.Features.RestoreIcps.Domain.RestoreIcpDetails", b =>
                {
                    b.HasOne("aseme_api.Features.RestoreIcps.Domain.RestoreIcp", "RestoreIcp")
                        .WithOne("RestoreIcpDetails")
                        .HasForeignKey("aseme_api.Features.RestoreIcps.Domain.RestoreIcpDetails", "RestoreIcpId");

                    b.Navigation("RestoreIcp");
                });

            modelBuilder.Entity("aseme_api.Features.RolesFunctionalities.Domain.RoleFunctionalities", b =>
                {
                    b.HasOne("aseme_api.Features.Functionalities.Domain.Functionality", "Functionality")
                        .WithMany("Roles")
                        .HasForeignKey("FunctionalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aseme_api.Features.Roles.Domain.Role", "Role")
                        .WithMany("Functionalities")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Functionality");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("aseme_api.Features.UsersRoles.Domain.UserRoles", b =>
                {
                    b.HasOne("aseme_api.Features.Users.Domain.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("LoginUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aseme_api.Features.Roles.Domain.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("aseme_api.Features.OnlineMeters.Domain.OnlineMeter", b =>
                {
                    b.HasOne("aseme_api.Features.Shared.Operation.BaseOperation", null)
                        .WithOne()
                        .HasForeignKey("aseme_api.Features.OnlineMeters.Domain.OnlineMeter", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aseme_api.Features.OnlineMeters.Domain.OnlineMeterDetails", "OnlineMeterDetails")
                        .WithMany()
                        .HasForeignKey("OnlineMeterDetailsOnlineMeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OnlineMeterDetails");
                });

            modelBuilder.Entity("aseme_api.Features.RestoreIcps.Domain.RestoreIcp", b =>
                {
                    b.HasOne("aseme_api.Features.Shared.Operation.BaseOperation", null)
                        .WithOne()
                        .HasForeignKey("aseme_api.Features.RestoreIcps.Domain.RestoreIcp", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("aseme_api.Features.Functionalities.Domain.Functionality", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("aseme_api.Features.Roles.Domain.Role", b =>
                {
                    b.Navigation("Functionalities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("aseme_api.Features.Users.Domain.User", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("aseme_api.Features.RestoreIcps.Domain.RestoreIcp", b =>
                {
                    b.Navigation("RestoreIcpDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
